name: sen
description: 'Sen: Environment'
publish_to: 'none'
version: 2.0.0
environment:
    sdk: '>=3.4.3 <4.0.0'
dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.6
    delightful_toast: ^1.1.0
    google_fonts: ^6.2.1
    shared_preferences: ^2.3.1
    ffi: ^2.1.2
    async: ^2.11.0
    material_symbols_icons: ^4.2777.1
    intl: any
    path: ^1.9.0
    window_manager: ^0.4.3
    desktop_drop: ^0.5.0
    image: ^4.2.0
    dynamic_color: ^1.7.0
    flutter_localizations:
        sdk: flutter
    page_transition: ^2.1.0
    flutter_local_notifications: ^18.0.0
    local_notifier: ^0.1.6
    flutter_launcher_icons: ^0.14.1
    file_selector: ^1.0.3
    url_launcher: ^6.3.1
    flutter_riverpod: ^2.6.1
    path_provider: ^2.1.5
    flutter_dotenv: ^5.2.1
    shimmer: ^3.0.0
    flutter_native_splash: ^2.4.3
dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^5.0.0
flutter_launcher_icons:
    android: true
    ios: true
    window: true
    linux: true
    macintosh: true
    image_path: 'assets/images/logo.png'
    remove_alpha_ios: true
flutter:
    uses-material-design: true
    generate: true
    assets:
        - assets/
        - assets/images/
        - assets/images/translator/
        - .env
    fonts:
        - family: GoogleSans
          fonts:
              - asset: assets/font/GoogleSans-Regular.ttf
        - family: Segoe UI
          fonts:
              - asset: assets/font/SegoeUI.ttf
