name: website
description: 'A new Flutter project.'
publish_to: 'none'
version: 1.0.0+1

environment:
    sdk: ^3.5.4
dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.8
    get_it: ^8.0.3
    flutter_riverpod: ^2.6.1
    material_symbols_icons: ^4.2801.0
    http: ^1.2.2
    hyperlink: ^0.0.5
    url_launcher_web: ^2.3.3
    firebase_core: ^3.8.1
    cloud_firestore: ^5.5.1

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^4.0.0
flutter:
    uses-material-design: true
    generate: true
    assets:
        - assets/
        - assets/images/
        - assets/images/dark/
        - assets/images/light/
        - assets/images/icons/
        - assets/images/logos/
    fonts:
        - family: GoogleSans
          fonts:
              - asset: assets/font/GoogleSans-Regular.ttf
